development: 
  cloud_name: "dp6r8zc2f"
  api_key: "774583318999224"
  api_secret: "uKsQPoBx6uwJ-uM9a_RPUVDe2dc"
  
production:
  cloud_name: "dp6r8zc2f"
  api_key: "774583318999224"
  api_secret: "uKsQPoBx6uwJ-uM9a_RPUVDe2dc"